### ISSUE TITLE
Add Support for Fantastical 3

### ISSUE THREAD

**Issue by seiz** [mailmate/fantastical.mmbundle#3]
This script doesn't do anything anymore since i upgraded to Fantastical 3. I tried to debug it, but unfortunately couldn't find any usefull error-logging anywhere on my system, so i have no idea where it broke.

**Comment by seiz** [comment]
Found the cause and could fix it locally by editing create_event and replacing `tell application "Fantastical 2"` with `tell application "Fantastical"`

**Comment by freron** [comment]
Thanks. I ended up fixing it by only using the application id. This should work for both Fantastical 2 and 3 although I haven't tested it for Fantastical 2.
I also swapped the ordering in the string to be parsed by Fantastical which I think will make it more likely that the Message-ID URL will *not* be part of the title of the event.

**Comment by seiz** [comment]
Great, thanks a lot! I currently have a case open with flexibits on a tip how one can achieve the previous behaviour, that MailMate caused the input for the new Event to be opened in the Mini-Window and not the big Window (as it seems to be since Fantastical V3). If they have a solution, i'll keep you posted here.

**Comment by freron** [comment]
Thanks, I had forgotten it worked differently before. I didn't see anything in the API I looked at, but I did notice that Fantastical 3 appears to have a URL scheme which might be more flexible/explicit than the current free text method.

**Comment by seiz** [comment]
I had looked at the Docs for the URL-Scheme but there isn't an option to define the mini-window as target for parsing a text-string for a new event. Unfortunately. We'll see what Flexbits have to say. I guess they have a lot of support-requests after the new release, so it might take a while…
